/**
 * Known FEATURE_* catalog + staging/prod deploy contract.
 *
 * Deploy expectations mirror .github/workflows/azure-deploy.yml as of the
 * FlagMatrix lane — FlagOps owns that file; this is a read-only document
 * of the contract for the admin UI.
 */

import type { FeatureFlagCatalogEntry } from "./types";

const unsetBoth = {
  staging: "unset" as const,
  production: "unset" as const,
};

export const FEATURE_FLAG_CATALOG: readonly FeatureFlagCatalogEntry[] = [
  // ── Critical: must match staging ↔ production ──────────────────────────
  {
    key: "FEATURE_OVERTURN_METRICS",
    description: "Overturn / trust calibration metrics",
    defaultWhenUnset: "off",
    critical: true,
    parity: "must_match",
    deploy: {
      staging: "true",
      production: "true",
      note: "Set unconditionally in azure-deploy Set environment variables",
    },
  },
  {
    key: "FEATURE_PHOTO_PAIR_COMPARE",
    description: "Photo pair evidence compare",
    defaultWhenUnset: "off",
    critical: true,
    parity: "must_match",
    deploy: {
      staging: "true",
      production: "true",
      note: "Set unconditionally in azure-deploy Set environment variables",
    },
  },
  {
    key: "FEATURE_PHOTO_PAIR_GEMINI",
    description: "Gemini multimodal before/after pair axes compare",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_SELECTION_MARKS",
    description: "Azure DI selection-marks / checklist pass",
    defaultWhenUnset: "conditional",
    critical: true,
    parity: "must_match",
    deploy: {
      staging: "conditional",
      production: "conditional",
      note: "Set true when AZURE_DI_KEY + AZURE_DI_ENDPOINT present (both envs)",
    },
  },
  {
    key: "FEATURE_COACHING_LLM_NARRATIVE",
    description: "Coaching pack LLM narrative (Anthropic)",
    defaultWhenUnset: "off",
    critical: true,
    parity: "must_match",
    deploy: {
      staging: "conditional",
      production: "conditional",
      note: "Set true when ANTHROPIC_API_KEY secret present (both envs)",
    },
  },
  {
    key: "FEATURE_COACHING_VERIFIER",
    description: "Coaching critic verifier (OpenAI)",
    defaultWhenUnset: "off",
    critical: true,
    parity: "must_match",
    deploy: {
      staging: "conditional",
      production: "conditional",
      note: "Set true when OPENAI_API_KEY secret present (both envs)",
    },
  },

  // ── Critical: intentionally divergent (prod promotion) ─────────────────
  {
    key: "FEATURE_VLM_VERIFICATION",
    description: "VLM ink / field verification",
    defaultWhenUnset: "off",
    critical: true,
    parity: "intentionally_divergent",
    deploy: {
      staging: "unset",
      production: "true",
      note: "Production-only in azure-deploy; staging omits until promoted",
    },
  },
  {
    key: "FEATURE_IMAGE_QA_INTAKE",
    description: "Image QA intake gate",
    defaultWhenUnset: "off",
    critical: true,
    parity: "intentionally_divergent",
    deploy: {
      staging: "unset",
      production: "true",
      note: "Production-only in azure-deploy; staging omits until promoted",
    },
  },
  {
    key: "FEATURE_GEMINI_MULTIMODAL",
    description: "Gemini multimodal ink path",
    defaultWhenUnset: "off",
    critical: true,
    parity: "intentionally_divergent",
    deploy: {
      staging: "unset",
      production: "true",
      note: "Production-only in azure-deploy; staging omits until promoted",
    },
  },

  // ── Catalogued (not set by azure-deploy by default) ────────────────────
  {
    key: "FEATURE_ASYNC_PROCESSING",
    description: "Async job-queue processing",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_CALIBRATION",
    description: "Calibration helpers",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_COHORT_BIAS",
    description: "Cohort bias analysis",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_COMMENT_LLM_ADVISORY",
    description: "Comment LLM advisory",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_FAULT_REASON_PLACEHOLDER",
    description:
      "Flag placeholder Fault Reason values as FAULT-C010 (default on)",
    defaultWhenUnset: "on",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_PARTS_LINE_ASSESSMENT",
    description: "Parts Used PN + description line pairing",
    defaultWhenUnset: "on",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_PARTS_WEB_VERIFY",
    description: "Exa parts catalog verify for PN vs description",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_CONFIDENCE_BANDS",
    description: "Confidence band mapping",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_CRITICAL_FIELD_EXTRACTOR",
    description: "Pipeline critical-field extractor",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_DETERMINISTIC_CACHE",
    description: "Pipeline deterministic cache",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_ENGINEER_FEEDBACK",
    description: "Pipeline engineer feedback",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_ENSEMBLE_EXTRACTION",
    description: "Ensemble extraction (enabled only when true)",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_FIELD_VOTE",
    description: "Multi-engine field voting + handwriting/VLM path",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_EVIDENCE_PACK",
    description: "Evidence pack export",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_FEEDBACK_LIVE",
    description: "Live feedback cadence",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_FIELD_DIFF",
    description: "Field diff helpers",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_FINDING_HYGIENE",
    description: "Finding hygiene pass",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_FINOPS",
    description: "FinOps throughput metrics",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_FIX_PACK_WORKFLOW",
    description: "Fix-pack workflow",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_GOLDEN_GROWTH",
    description: "Golden-set growth from corrections",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_FIELD_F1_GATE",
    description: "Field exact-match F1 measurement artifact",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_ATTRIBUTION_SLO",
    description: "Technician attribution unattributed-rate SLO",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_ENGINEER_ATTR_FINDING",
    description: "Engineer name attribution gap findings (ATTR-C010–C012)",
    defaultWhenUnset: "on",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_HOLD_SLA",
    description: "Hold-queue SLA helpers",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_IDEMPOTENCY",
    description: "Processing idempotency guards",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_IMAGE_QA_FUSION",
    description: "Pipeline image-QA fusion",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_LATENCY_BUDGET",
    description: "Latency budget tracking",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_OCR_CROSS_CHECK",
    description: "OCR cross-check",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_OCR_FAILOVER",
    description: "OCR provider failover",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_OPS_ALERTS",
    description: "Ops attention / drift alerts",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_OVERTURN_COST",
    description: "Overturn cost estimates",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_PIPELINE_INTEGRATION",
    description: "Pipeline integration master flag",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_PROMOTION_SCORE",
    description: "Template promotion score",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_QUOTA_GUARD",
    description: "Quota window guards",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_REDACTION",
    description: "PII redaction helpers",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_RELEASE_BAR",
    description: "Release / quarantine bar",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_RETRY_POLICY",
    description: "Retry / backoff policy",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_REVIEW_LOAD",
    description: "Reviewer load balancing",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_RISK_ROUTING",
    description: "Risk-based routing",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_SAMPLING_POLICY",
    description: "Sampling policy",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_SEVERITY_NORMALIZE",
    description: "Severity normalization",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_SHADOW_CHALLENGER",
    description: "Shadow challenger mode",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_SHADOW_REAL_MODEL",
    description: "Shadow challenger real-model path",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_STAGE_SLO",
    description: "Per-stage SLO budgets",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_AZURE_DI_CUSTOM_JSR",
    description: "Azure DI custom neural JSR voter",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_DURABLE_JOB_QUEUE",
    description: "MySQL-backed durable job queue (requires async processing)",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_MULTIMODAL_ROI_EXTRACT",
    description: "Gemini structured extraction from ROI crops",
    defaultWhenUnset: "conditional",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_ROI_CROP_REOCR",
    description: "Mistral OCR pass for configured PDF ROI crops",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
  {
    key: "FEATURE_TEMPLATE_COLLISION",
    description: "Template fingerprint collision checks",
    defaultWhenUnset: "off",
    critical: false,
    parity: "unspecified",
    deploy: unsetBoth,
  },
];

export const KEY_ENV_CATALOG: readonly {
  key: string;
  description: string;
  secret?: boolean;
}[] = [
  { key: "APP_ENV", description: "Application environment identity" },
  { key: "NODE_ENV", description: "Node runtime mode" },
  { key: "STORAGE_PROVIDER", description: "Storage adapter (local|azure)" },
  {
    key: "AZURE_STORAGE_CONTAINER_NAME",
    description: "Blob container name",
  },
  {
    key: "ENABLE_PURGE_EXECUTION",
    description: "Safety: allow purge execution",
  },
  { key: "ENABLE_SCHEDULER", description: "Safety: background scheduler" },
  {
    key: "ENABLE_GEMINI_INSIGHTS",
    description: "Gemini insights toggle",
  },
  { key: "VLM_PROVIDER", description: "VLM provider (e.g. anthropic)" },
  {
    key: "TEMPLATE_REGISTRY_MYSQL_PERSISTENCE_ENABLED",
    description: "Template registry MySQL persistence",
  },
  { key: "GIT_SHA", description: "Deployed git SHA" },
  { key: "PLATFORM_VERSION", description: "Platform version label" },
  {
    key: "MISTRAL_API_KEY",
    description: "Mistral OCR key",
    secret: true,
  },
  { key: "GEMINI_API_KEY", description: "Gemini key", secret: true },
  {
    key: "ANTHROPIC_API_KEY",
    description: "Anthropic / VLM key",
    secret: true,
  },
  { key: "OPENAI_API_KEY", description: "OpenAI verifier key", secret: true },
  {
    key: "AZURE_DI_ENDPOINT",
    description: "Azure Document Intelligence endpoint",
  },
  {
    key: "AZURE_DI_KEY",
    description: "Azure Document Intelligence key",
    secret: true,
  },
];
