/**
 * Base Specification Pack
 * 
 * Default rules and fields for job sheet validation.
 * All other packs extend from this base.
 */

import type { SpecPack } from '../types';

export const baseSpecPack: SpecPack = {
  id: 'base',
  version: '1.0.0',
  name: 'Base Job Sheet Specification',
  description: 'Default validation rules and field definitions for job sheets',
  
  fields: [
    {
      field: 'jobNumber',
      label: 'Job Number',
      type: 'string',
      required: true,
      extractionHints: ['Job #', 'Job No', 'Job Number', 'Work Order'],
      aliases: ['job_number', 'jobNo', 'workOrder'],
    },
    {
      field: 'customerName',
      label: 'Customer Name',
      type: 'string',
      required: true,
      extractionHints: ['Customer', 'Client', 'Bill To', 'Customer Name'],
      aliases: ['customer_name', 'client', 'billTo'],
    },
    {
      field: 'jobDate',
      label: 'Job Date',
      type: 'date',
      required: true,
      extractionHints: ['Date', 'Job Date', 'Service Date', 'Work Date'],
      aliases: ['job_date', 'serviceDate', 'date'],
    },
    {
      field: 'technicianName',
      label: 'Technician Name',
      type: 'string',
      required: true,
      extractionHints: ['Technician', 'Tech', 'Service Tech', 'Performed By'],
      aliases: ['technician_name', 'tech', 'performedBy'],
    },
    {
      field: 'serviceAddress',
      label: 'Service Address',
      type: 'string',
      required: true,
      extractionHints: ['Address', 'Service Address', 'Location', 'Site'],
      aliases: ['service_address', 'address', 'location'],
    },
    {
      field: 'workDescription',
      label: 'Work Description',
      type: 'string',
      required: true,
      extractionHints: ['Description', 'Work Performed', 'Services', 'Details'],
      aliases: ['work_description', 'description', 'workPerformed'],
    },
    {
      field: 'totalAmount',
      label: 'Total Amount',
      type: 'currency',
      required: false,
      extractionHints: ['Total', 'Amount', 'Total Due', 'Grand Total'],
      aliases: ['total_amount', 'total', 'amount'],
    },
    {
      field: 'customerSignature',
      label: 'Customer Signature',
      type: 'boolean',
      required: false,
      extractionHints: ['Signature', 'Customer Signature', 'Signed'],
      aliases: ['customer_signature', 'signature', 'signed'],
    },
    {
      field: 'technicianSignature',
      label: 'Technician Signature',
      type: 'boolean',
      required: false,
      extractionHints: ['Tech Signature', 'Technician Signature'],
      aliases: ['technician_signature', 'techSignature'],
    },
    {
      field: 'completionTime',
      label: 'Completion Time',
      type: 'string',
      required: false,
      extractionHints: ['Time', 'Completion Time', 'End Time', 'Finished'],
      aliases: ['completion_time', 'endTime', 'time'],
    },
  ],
  
  rules: [
    {
      ruleId: 'R001',
      field: 'jobNumber',
      description: 'Job number is required',
      severity: 'critical',
      type: 'required',
      enabled: true,
      tags: ['required', 'identification'],
    },
    {
      ruleId: 'R002',
      field: 'jobNumber',
      description: 'Job number must match expected format',
      severity: 'major',
      type: 'pattern',
      pattern: '^[A-Z]{2,3}-?\\d{3,8}$',
      enabled: true,
      tags: ['format', 'identification'],
    },
    {
      ruleId: 'R003',
      field: 'customerName',
      description: 'Customer name is required',
      severity: 'critical',
      type: 'required',
      enabled: true,
      tags: ['required', 'customer'],
    },
    {
      ruleId: 'R004',
      field: 'jobDate',
      description: 'Job date is required',
      severity: 'critical',
      type: 'required',
      enabled: true,
      tags: ['required', 'date'],
    },
    {
      ruleId: 'R005',
      field: 'jobDate',
      description: 'Job date must be valid',
      severity: 'major',
      type: 'format',
      pattern: '^\\d{4}-\\d{2}-\\d{2}$|^\\d{1,2}/\\d{1,2}/\\d{2,4}$',
      enabled: true,
      tags: ['format', 'date'],
    },
    {
      ruleId: 'R006',
      field: 'technicianName',
      description: 'Technician name is required',
      severity: 'critical',
      type: 'required',
      enabled: true,
      tags: ['required', 'technician'],
    },
    {
      ruleId: 'R007',
      field: 'serviceAddress',
      description: 'Service address is required',
      severity: 'critical',
      type: 'required',
      enabled: true,
      tags: ['required', 'location'],
    },
    {
      ruleId: 'R008',
      field: 'workDescription',
      description: 'Work description is required',
      severity: 'critical',
      type: 'required',
      enabled: true,
      tags: ['required', 'work'],
    },
    {
      ruleId: 'R009',
      field: 'workDescription',
      description: 'Work description must be at least 10 characters',
      severity: 'minor',
      type: 'custom',
      customValidator: 'minLength:10',
      enabled: true,
      tags: ['quality', 'work'],
    },
    {
      ruleId: 'R010',
      field: 'totalAmount',
      description: 'Total amount must be a valid currency value',
      severity: 'major',
      type: 'pattern',
      pattern: '^\\$?[\\d,]+(\\.\\d{2})?$',
      enabled: true,
      tags: ['format', 'financial'],
    },
    {
      ruleId: 'R011',
      field: 'customerSignature',
      description: 'Customer signature is recommended',
      severity: 'info',
      type: 'required',
      enabled: true,
      tags: ['signature', 'customer'],
    },
    {
      ruleId: 'R012',
      field: 'technicianSignature',
      description: 'Technician signature is recommended',
      severity: 'info',
      type: 'required',
      enabled: true,
      tags: ['signature', 'technician'],
    },
  ],
  
  metadata: {
    author: 'System',
    createdAt: '2024-01-01T00:00:00.000Z',
    tags: ['base', 'default'],
  },
};
