import { useState } from "react";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
  CardFooter,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";
import { Mail, Eye, RefreshCw, User, Users } from "lucide-react";

interface EmailTemplate {
  id: string;
  name: string;
  subject: string;
  description: string;
  aiPrompt: string;
  targetAudience: "stakeholders" | "engineers";
  frequency: "daily" | "weekly";
  isActive: boolean;
}

const DEFAULT_TEMPLATES: EmailTemplate[] = [
  {
    id: "daily-summary",
    name: "Daily Stakeholder Summary",
    subject: "Job Sheet QA - Daily Performance Digest",
    description:
      "High-level overview of daily audit performance, critical defects, and hold queue status.",
    aiPrompt:
      "Generate a professional daily summary email for stakeholders. Include: Total audits processed, pass rate trend, top 3 critical defects found today, and current hold queue volume. Tone: Professional, concise, data-driven.",
    targetAudience: "stakeholders",
    frequency: "daily",
    isActive: true,
  },
  {
    id: "weekly-engineer",
    name: "Weekly Engineer Performance",
    subject: "Your Weekly Quality Scorecard",
    description:
      "Personalized performance report for each engineer with scores, trends, and improvement tips.",
    aiPrompt:
      "Generate a personalized weekly email for an engineer. Include: Their personal pass rate vs team average, list of their most common defect types this week, and one specific actionable tip for improvement. Tone: Encouraging, constructive, coaching-oriented.",
    targetAudience: "engineers",
    frequency: "weekly",
    isActive: true,
  },
];

function sampleLayoutHtml(template: EmailTemplate): string {
  if (template.id === "daily-summary") {
    return `
          <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden;">
            <div style="background-color: #0f172a; padding: 20px; text-align: center;">
              <h2 style="color: #ffffff; margin: 0;">Daily Performance Digest</h2>
              <p style="color: #94a3b8; margin: 5px 0 0;">Sample date</p>
            </div>
            <div style="padding: 24px; background-color: #ffffff;">
              <p>Dear Stakeholders,</p>
              <p>Placeholder body for the daily digest layout. Numbers below are static sample values, not live data.</p>
              
              <div style="display: flex; gap: 16px; margin: 24px 0;">
                <div style="flex: 1; background: #f8fafc; padding: 16px; border-radius: 8px; text-align: center;">
                  <div style="font-size: 24px; font-weight: bold; color: #0f172a;">—</div>
                  <div style="font-size: 12px; color: #64748b;">Audits Processed</div>
                </div>
                <div style="flex: 1; background: #f0fdf4; padding: 16px; border-radius: 8px; text-align: center;">
                  <div style="font-size: 24px; font-weight: bold; color: #16a34a;">—</div>
                  <div style="font-size: 12px; color: #64748b;">Pass Rate</div>
                </div>
                <div style="flex: 1; background: #fef2f2; padding: 16px; border-radius: 8px; text-align: center;">
                  <div style="font-size: 24px; font-weight: bold; color: #dc2626;">—</div>
                  <div style="font-size: 12px; color: #64748b;">Critical Defects</div>
                </div>
              </div>

              <h3 style="font-size: 16px; color: #334155; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px;">Top Critical Defects</h3>
              <ul style="color: #475569; padding-left: 20px;">
                <li>Sample defect A</li>
                <li>Sample defect B</li>
              </ul>

              <div style="margin-top: 24px; padding: 16px; background-color: #fff7ed; border-left: 4px solid #f97316; border-radius: 4px;">
                <strong>Hold Queue Status:</strong> Placeholder — no live queue data in this preview.
              </div>
            </div>
            <div style="background-color: #f1f5f9; padding: 16px; text-align: center; font-size: 12px; color: #64748b;">
              Sample layout only — not generated by AI.
            </div>
          </div>
        `;
  }

  return `
          <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden;">
            <div style="background-color: #2563eb; padding: 20px; text-align: center;">
              <h2 style="color: #ffffff; margin: 0;">Weekly Scorecard</h2>
              <p style="color: #bfdbfe; margin: 5px 0 0;">Sample week</p>
            </div>
            <div style="padding: 24px; background-color: #ffffff;">
              <p>Hi [Engineer],</p>
              <p>Placeholder body for the weekly scorecard layout. Metrics below are static samples, not live data.</p>
              
              <div style="margin: 24px 0; padding: 20px; background: #eff6ff; border-radius: 12px; text-align: center;">
                <div style="font-size: 14px; color: #1e40af; margin-bottom: 8px;">Your Pass Rate</div>
                <div style="font-size: 48px; font-weight: bold; color: #1d4ed8;">—</div>
                <div style="font-size: 14px; color: #1e40af; margin-top: 4px;">Team Avg: —</div>
              </div>

              <h3 style="font-size: 16px; color: #334155;">Focus Area for Next Week</h3>
              <p style="color: #475569; line-height: 1.5;">
                Coaching tip placeholder. AI generation is not wired yet.
              </p>
            </div>
            <div style="background-color: #f1f5f9; padding: 16px; text-align: center; font-size: 12px; color: #64748b;">
              Sample layout only — not generated by AI.
            </div>
          </div>
        `;
}

export function EmailTemplateManager() {
  const [templates, setTemplates] =
    useState<EmailTemplate[]>(DEFAULT_TEMPLATES);
  const [selectedTemplateId, setSelectedTemplateId] = useState<string>(
    DEFAULT_TEMPLATES[0].id
  );
  const [previewContent, setPreviewContent] = useState<string | null>(null);

  const selectedTemplate =
    templates.find(t => t.id === selectedTemplateId) || templates[0];

  const handleUpdateTemplate = (
    key: keyof EmailTemplate,
    value: EmailTemplate[keyof EmailTemplate]
  ) => {
    setTemplates(prev =>
      prev.map(t => (t.id === selectedTemplateId ? { ...t, [key]: value } : t))
    );
  };

  const showSampleLayout = () => {
    setPreviewContent(sampleLayoutHtml(selectedTemplate));
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 h-[calc(100vh-12rem)]">
      {/* Sidebar List */}
      <div className="lg:col-span-3 space-y-4">
        <Card className="h-full">
          <CardHeader>
            <CardTitle className="text-lg">Templates</CardTitle>
          </CardHeader>
          <CardContent className="p-2">
            <div className="space-y-2">
              {templates.map(template => (
                <div
                  key={template.id}
                  onClick={() => {
                    setSelectedTemplateId(template.id);
                    setPreviewContent(null);
                  }}
                  className={`p-3 rounded-md cursor-pointer transition-colors border ${
                    selectedTemplateId === template.id
                      ? "bg-primary/10 border-primary"
                      : "hover:bg-muted border-transparent"
                  }`}
                >
                  <div className="flex justify-between items-start mb-1">
                    <span className="font-medium text-sm">{template.name}</span>
                    {template.isActive && (
                      <span className="w-2 h-2 rounded-full bg-green-500 mt-1.5" />
                    )}
                  </div>
                  <div className="flex items-center gap-2 text-xs text-muted-foreground">
                    {template.targetAudience === "stakeholders" ? (
                      <Users className="w-3 h-3" />
                    ) : (
                      <User className="w-3 h-3" />
                    )}
                    <span className="capitalize">{template.frequency}</span>
                  </div>
                </div>
              ))}
              <Button
                variant="outline"
                className="w-full mt-4 border-dashed"
                disabled
                title="Creating templates is not wired yet"
              >
                <span className="mr-2">+</span> New Template (not wired)
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Editor Area */}
      <div className="lg:col-span-5 space-y-4">
        <Card className="h-full flex flex-col">
          <CardHeader>
            <div className="flex justify-between items-center">
              <CardTitle>Template Editor</CardTitle>
              <div className="flex items-center gap-2">
                <Label htmlFor="active-mode" className="text-xs">
                  Active (local only)
                </Label>
                <Switch
                  id="active-mode"
                  checked={selectedTemplate.isActive}
                  onCheckedChange={checked =>
                    handleUpdateTemplate("isActive", checked)
                  }
                />
              </div>
            </div>
            <CardDescription>
              Draft prompts and schedule locally. AI generation and outbound
              mail are not wired yet — changes are not saved.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4 flex-1 overflow-auto">
            <div className="space-y-2">
              <Label>Template Name</Label>
              <Input
                value={selectedTemplate.name}
                onChange={e => handleUpdateTemplate("name", e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label>Email Subject Line</Label>
              <Input
                value={selectedTemplate.subject}
                onChange={e => handleUpdateTemplate("subject", e.target.value)}
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Target Audience</Label>
                <select
                  className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                  value={selectedTemplate.targetAudience}
                  onChange={e =>
                    handleUpdateTemplate(
                      "targetAudience",
                      e.target.value as EmailTemplate["targetAudience"]
                    )
                  }
                >
                  <option value="stakeholders">Stakeholders</option>
                  <option value="engineers">Engineers</option>
                </select>
              </div>
              <div className="space-y-2">
                <Label>Frequency</Label>
                <select
                  className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                  value={selectedTemplate.frequency}
                  onChange={e =>
                    handleUpdateTemplate(
                      "frequency",
                      e.target.value as EmailTemplate["frequency"]
                    )
                  }
                >
                  <option value="daily">Daily</option>
                  <option value="weekly">Weekly</option>
                  <option value="monthly">Monthly</option>
                </select>
              </div>
            </div>

            <div className="space-y-2">
              <div className="flex justify-between items-center">
                <Label>Content prompt (draft)</Label>
                <Badge variant="outline" className="text-[10px]">
                  Not connected
                </Badge>
              </div>
              <Textarea
                className="min-h-[200px] font-mono text-sm"
                value={selectedTemplate.aiPrompt}
                onChange={e => handleUpdateTemplate("aiPrompt", e.target.value)}
                placeholder="Describe how the email should read when generation is wired..."
              />
              <p className="text-xs text-muted-foreground">
                Prompt text is edited locally only. No model is called from this
                screen.
              </p>
            </div>
          </CardContent>
          <CardFooter className="border-t p-4 flex justify-between">
            <Button
              variant="ghost"
              onClick={() => {
                setTemplates(DEFAULT_TEMPLATES);
                setPreviewContent(null);
              }}
            >
              <RefreshCw className="w-4 h-4 mr-2" />
              Reset
            </Button>
            <Button variant="outline" onClick={showSampleLayout}>
              <Eye className="w-4 h-4 mr-2" />
              Show sample layout
            </Button>
          </CardFooter>
        </Card>
      </div>

      {/* Preview Area */}
      <div className="lg:col-span-4 space-y-4">
        <Card className="h-full flex flex-col bg-muted/30">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Sample layout
            </CardTitle>
            <CardDescription className="text-xs">
              Static placeholder HTML — not AI output and not live data.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex-1 overflow-auto p-4">
            {previewContent ? (
              <div>
                <div className="mb-4 text-sm border-b pb-2">
                  <div className="flex gap-2 mb-1">
                    <span className="text-muted-foreground w-12">To:</span>
                    <span className="font-medium text-muted-foreground">
                      {selectedTemplate.targetAudience === "stakeholders"
                        ? "(audience: stakeholders)"
                        : "(audience: engineers)"}
                    </span>
                  </div>
                  <div className="flex gap-2">
                    <span className="text-muted-foreground w-12">Subject:</span>
                    <span className="font-medium">
                      {selectedTemplate.subject}
                    </span>
                  </div>
                </div>
                <div
                  className="preview-container bg-white shadow-sm rounded-lg"
                  dangerouslySetInnerHTML={{ __html: previewContent }}
                />
              </div>
            ) : (
              <div className="h-full flex flex-col items-center justify-center text-muted-foreground space-y-3 opacity-50">
                <Mail className="w-12 h-12" />
                <p className="text-sm text-center max-w-[220px]">
                  Click &quot;Show sample layout&quot; for a static HTML sketch
                  of this template. AI preview is not available.
                </p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
